### ISSUE TITLE
Redirect the thumbnail link to the post instead of the user profile

### ISSUE THREAD

**Issue by iamdarkle** [FriendsOfFlarum/discussion-thumbnail#12]
## Feature Request

As has already been mentioned in the discussion on a few times, I think it would be a great idea to include a switch in the admin panel or make the default option of the post thumbnails instead of redirecting to the user's profile redirect to the post itself. It is very unintuitive/confusing that clicking on an image related to the post ends up taking you to a user's profile.

**Comment by dsevillamartin** [comment]
Added in v1.1.0
